apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '11'
  labels:
    gitops.ownedBy: cluster-config
  name: config-helm-repos
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/configs/helm-repos/base
    repoURL: https://github.com/salanisor/cluster-config.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
