# Assumes the cluster admin had pre-created the infrastructure nodes.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: Prune=false

resources:
- reg-nfs.yaml
- reg-pvc.yaml
- ingress-registry.yaml
