apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
  namespace: openshift-image-registry
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /opt/exports/nfs
    server: 192.168.8.2
