# Assumes the cluster admin had pre-created the infrastructure nodes.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-monitoring

#commonAnnotations:
#  argocd.argoproj.io/compare-options: IgnoreExtraneous
#  argocd.argoproj.io/sync-options: Prune=false

resources:
- ingress-monitoring.yaml
