kind: Application
metadata:
  name: config-pipeline-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/openshift-pipelines/base
    repoURL: https://github.com/salanisor/cluster-config.git
    targetRevision: openshift-virtualization
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
