apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: argocd
spec:
  href: 'https://argocd-server-argocd.apps.keights.org'
  location: ApplicationMenu
  text: ArgoCD
  applicationMenu:
    section: Tools
    imageURL: https://raw.githubusercontent.com/salanisor/cluster-config/master/docs/img/argocd-logo.png