apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '3'
  labels:
    gitops.ownedBy: cluster-config
  name: openshift-virtualization
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/openshift-pipelines/base/
    repoURL: https://github.com/salanisor/cluster-config.git
    targetRevision: openshift-virtualization
  syncPolicy:
    automated:
      selfHeal: true
