apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"hco.kubevirt.io/v1beta1","kind":"HyperConverged","metadata":{"annotations":{},"labels":{"app":"kubevirt-hyperconverged"},"name":"kubevirt-hyperconverged","namespace":"openshift-cnv"},"spec":{"featureGates":{"deployTektonTaskResources":true,"enableCommonBootImageImport":true,"nonRoot":true,"sriovLiveMigration":true,"withHostPassthroughCPU":false},"tektonPipelinesNamespace":"cnv-pipelines"}}
  labels:
    app: kubevirt-hyperconverged
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  certConfig:
    ca:
      duration: 48h0m0s
      renewBefore: 24h0m0s
    server:
      duration: 24h0m0s
      renewBefore: 12h0m0s
  featureGates:
    deployTektonTaskResources: true
    enableCommonBootImageImport: true
    nonRoot: true
    sriovLiveMigration: true
    withHostPassthroughCPU: false
  infra: {}
  liveMigrationConfig:
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  tektonPipelinesNamespace: cnv-pipelines
  uninstallStrategy: BlockUninstallIfWorkloadsExist
  workloadUpdateStrategy:
    batchEvictionInterval: 1m0s
    batchEvictionSize: 10
    workloadUpdateMethods:
    - LiveMigrate
  workloads: {}
status: {}
