apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-openshift-virtualization
  annotations:
    argocd.argoproj.io/sync-wave: "21"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/apps/config-openshift-virtualization/overlays/default
    repoURL: https://github.com/gnunn-gitops/cluster-config.git
    targetRevision: openshift-virtualization
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
