apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
  name: config-serverless
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/argocd/apps/config-serverless/base
    repoURL: https://github.com/salanisor/cluster-config.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
